// =============================================================================
//  /api/enquiry/_lib/routing/_templates/agent-email.js
// =============================================================================
//
//  Default HTML email sent to the agent when a new submission lands.
//  Used when the form has no custom Routing Email Template HTML set.
//
//  EMAIL HTML RULES (different from web):
//  - Table-based layout only (flexbox/grid unsupported in Outlook)
//  - Inline styles only (<style> blocks stripped by Gmail, others)
//  - No external CSS, no external fonts (use web-safe stack)
//  - Width max 600px, responsive via table widths + Media Query for mobile
//  - Images with absolute URLs, width/height attributes
//  - Plain text fallback should be generated by caller
//
//  Brand colours applied via the token system (Travelgenix navy + cyan).
//
// =============================================================================

// HTML-escape every token value before interpolation
function esc(s) {
  if (s === null || s === undefined) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Render a single summary row in the details table
function row(label, value) {
  return `
    <tr>
      <td style="padding:12px 20px;border-bottom:1px solid #F1F5F9;color:#94A3B8;font-size:12px;text-transform:uppercase;letter-spacing:0.06em;font-weight:500;vertical-align:top;width:140px;">${esc(label)}</td>
      <td style="padding:12px 20px;border-bottom:1px solid #F1F5F9;color:#0F172A;font-size:14px;font-weight:500;">${esc(value)}</td>
    </tr>`;
}

export function renderDefaultAgentEmail(t) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>New enquiry ${esc(t.reference)}</title>
</head>
<body style="margin:0;padding:0;background:#F8FAFC;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">

  <!-- Preheader (hidden in the inbox preview) -->
  <div style="display:none;max-height:0;overflow:hidden;font-size:1px;line-height:1px;color:#F8FAFC;">
    New enquiry from ${esc(t.fullName)} — ${esc(t.destinations)}, ${esc(t.duration)}. Reference ${esc(t.reference)}.
  </div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F8FAFC;">
    <tr>
      <td align="center" style="padding:32px 16px;">

        <!-- Main card -->
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(15,23,42,0.06);">

          <!-- Header bar -->
          <tr>
            <td style="background:linear-gradient(135deg,#1B2B5B,#2A3F7A);padding:28px 32px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td>
                    <div style="color:#00B4D8;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:8px;">New enquiry</div>
                    <div style="color:#FFFFFF;font-size:22px;font-weight:700;line-height:1.3;">${esc(t.fullName)}</div>
                    <div style="color:#CBD5E1;font-size:14px;margin-top:4px;">${esc(t.destinations)} · ${esc(t.duration)}</div>
                  </td>
                  <td align="right" style="vertical-align:top;">
                    <div style="color:#94A3B8;font-size:11px;text-transform:uppercase;letter-spacing:0.06em;">Reference</div>
                    <div style="color:#FFFFFF;font-size:13px;font-weight:600;font-family:'SF Mono',Menlo,Consolas,monospace;margin-top:2px;">${esc(t.reference)}</div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Intro line -->
          <tr>
            <td style="padding:24px 32px 8px;">
              <p style="margin:0;color:#475569;font-size:14px;line-height:1.6;">
                A new enquiry has come through your <strong style="color:#0F172A;">${esc(t.formName)}</strong> form. Full details below. Hit reply to respond directly to the customer.
              </p>
            </td>
          </tr>

          <!-- Quick contact block -->
          <tr>
            <td style="padding:16px 32px 0;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:12px;">
                <tr>
                  <td style="padding:16px 20px;">
                    <div style="color:#94A3B8;font-size:11px;text-transform:uppercase;letter-spacing:0.06em;font-weight:500;margin-bottom:6px;">Customer contact</div>
                    <div style="color:#0F172A;font-size:16px;font-weight:600;">${esc(t.fullName)}</div>
                    <div style="margin-top:4px;">
                      <a href="mailto:${esc(t.email)}" style="color:#0096B7;font-size:14px;text-decoration:none;font-weight:500;">${esc(t.email)}</a>
                      ${t.phone && t.phone !== '—' ? `<span style="color:#CBD5E1;margin:0 8px;">·</span><a href="tel:${esc(t.phone)}" style="color:#0096B7;font-size:14px;text-decoration:none;font-weight:500;">${esc(t.phone)}</a>` : ''}
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Enquiry details -->
          <tr>
            <td style="padding:24px 32px 8px;">
              <h2 style="margin:0 0 12px;color:#0F172A;font-size:15px;font-weight:600;">Enquiry details</h2>
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #E2E8F0;border-radius:12px;overflow:hidden;">
                ${row('Destination', t.destinations)}
                ${row('Departing from', t.departureAirport)}
                ${row('Dates', t.dates)}
                ${row('Duration', t.duration)}
                ${row('Travellers', t.travellers)}
                ${row('Budget', t.budget)}
                ${row('Style', `${t.stars} · ${t.boardBasis}`)}
                ${t.interests !== '—' ? row('Interests', t.interests) : ''}
              </table>
            </td>
          </tr>

          ${t.notes && t.notes !== '—' ? `
          <!-- Notes -->
          <tr>
            <td style="padding:16px 32px 8px;">
              <h2 style="margin:0 0 12px;color:#0F172A;font-size:15px;font-weight:600;">Notes from the customer</h2>
              <div style="padding:16px 20px;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:12px;color:#475569;font-size:14px;line-height:1.6;white-space:pre-wrap;">${esc(t.notes)}</div>
            </td>
          </tr>` : ''}

          <!-- CTA -->
          <tr>
            <td align="center" style="padding:24px 32px 8px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="border-radius:8px;background:#1B2B5B;">
                    <a href="mailto:${esc(t.email)}?subject=Re:%20your%20enquiry%20${esc(t.reference)}" style="display:inline-block;padding:14px 28px;color:#FFFFFF;font-size:14px;font-weight:600;text-decoration:none;border-radius:8px;">
                      Reply to ${esc(t.firstName)}
                    </a>
                  </td>
                </tr>
              </table>
              <div style="margin-top:12px;color:#94A3B8;font-size:12px;">
                Or <a href="${esc(t.submissionUrl)}" style="color:#0096B7;text-decoration:none;">view this enquiry in Airtable</a>
              </div>
            </td>
          </tr>

          <!-- Footer meta -->
          <tr>
            <td style="padding:24px 32px 28px;">
              <div style="padding-top:16px;border-top:1px solid #F1F5F9;color:#94A3B8;font-size:12px;line-height:1.6;">
                Submitted ${esc(t.submittedAt)} · ${t.sourceUrl ? `Source: <a href="${esc(t.sourceUrl)}" style="color:#94A3B8;">${esc(t.sourceUrl)}</a>` : 'Direct'}
                <br>
                Powered by Travelgenix Enquiry Forms. <a href="https://tg-widgets.vercel.app" style="color:#94A3B8;">Manage forms</a>
              </div>
            </td>
          </tr>
        </table>

      </td>
    </tr>
  </table>

</body>
</html>`;
}
