/**
 * The tags a published page needs from its site settings.
 *
 * Two server components with no interactivity. React hoists link, meta and script
 * into the document head, so these sit next to the content they apply to rather
 * than being threaded up through a layout, exactly like FontHead.
 *
 * ALL THE DECISIONS ARE IN lib/settings/head.ts, which is pure and tested. This
 * file only renders what that hands back, so there is nothing here to get wrong
 * that a unit test could not have caught.
 *
 * WHY THE STAFF HTML IS RENDERED HERE AND NOT IN THE PREVIEW
 *
 * The preview at /preview shares an origin with the editor, so raw HTML executing
 * there could read the editor's session cookies. On a client's own hostname it is a
 * different origin and can do nothing of the sort. So these components are used by
 * the site route and NOT by the preview route, and that is a security boundary
 * rather than an oversight: the comment is here because "why is the preview
 * missing the chat widget" is a reasonable question with a real answer.
 */

import type { ReactElement } from 'react';

import { analytics, iconLinks } from '../../lib/settings/head';
import type { PublicSiteSettings } from '../../lib/db/settings';

interface Props {
  settings: PublicSiteSettings;
}

export function SiteHead({ settings }: Props): ReactElement {
  const links = iconLinks(settings);
  const tags = analytics(settings);

  return (
    <>
      {links.map((link) => (
        <link
          key={`${link.rel}:${link.href}`}
          rel={link.rel}
          href={link.href}
          sizes={link.sizes}
          type={link.type}
        />
      ))}

      {/*
        The external tag script. async, because nothing on the page waits for
        analytics and a blocking third-party script is the single most common way a
        fast page becomes a slow one.
      */}
      {tags.headSrc.map((src) => (
        // eslint-disable-next-line @next/next/no-sync-scripts
        <script key={src} async src={src} />
      ))}

      {/*
        The inline snippets, built from validated ids. dangerouslySetInnerHTML is
        the only way to put script text in the document, and what makes it
        acceptable here is that the string was generated by lib/settings/head.ts
        from an id matched against /^GTM-[A-Z0-9]{4,12}$/. Nothing a client typed
        reaches it unchecked, which is the same argument FontHead makes about its
        style tag.
      */}
      {tags.headInline.map((code, index) => (
        <script key={index} dangerouslySetInnerHTML={{ __html: code }} />
      ))}

      {/*
        The site's own head HTML, last of the head.
        Raw and unsanitised on purpose: it is written only by an action that requires
        the site's owner or Travelgenix staff, and sanitising it would strip the
        script tag that is the only reason the field exists. See
        lib/settings/schema.ts.
      */}
      {settings.headHtml ? <span dangerouslySetInnerHTML={{ __html: settings.headHtml }} /> : null}
    </>
  );
}

/**
 * The end of the body: the tag manager's noscript fallback, and the site's own body
 * HTML.
 *
 * Separate component rather than a prop on SiteHead, because it renders in a
 * different place in the tree and a single component returning two fragments for
 * two positions is not a thing React can do.
 */
export function SiteBody({ settings }: Props): ReactElement | null {
  const tags = analytics(settings);
  if (tags.bodyMarkup.length === 0 && !settings.bodyHtml) return null;

  return (
    <>
      {tags.bodyMarkup.map((markup, index) => (
        <div key={index} dangerouslySetInnerHTML={{ __html: markup }} />
      ))}
      {settings.bodyHtml ? <div dangerouslySetInnerHTML={{ __html: settings.bodyHtml }} /> : null}
    </>
  );
}
